version: '3'
services:
  vulnerable-app:
    build: .
    ports:
      - "5000:5000"
    networks:
      - vulnnet

  sqlmap:
    image: marsko/vulnerable-app:latest
    depends_on:
      - vulnerable-app
    networks:
      - vulnnet
    entrypoint: >
      sh -c "
      sleep 10 && 
      sqlmap -u http://vulnerable-app:5000/login --data='username=test&password=test' --batch --level=5 --risk=3 --random-agent
      "

networks:
  vulnnet:
